services:
  app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ENABLECORS: "false"
